In [13]:
from torch.autograd import Variable
import torch
import numpy as np
import math


def NLL_loss(mu: Variable, sigma: Variable, labels: Variable):
    """
    Negative Log Likelihood loss function.
    Compute using gaussian the log-likehood which needs to be maximized. 
    Ignore time steps where labels are missing.

    Args:
        mu: (Variable) dimension [batch_size] - estimated mean at time step t
        sigma: (Variable) dimension [batch_size] - estimated standard deviation at time step t
        labels: (Variable) dimension [batch_size] z_t
    Returns:
        loss: (Variable) average log-likelihood loss across the batch
    """
    # TODO: commented out zero_index since we also want to overfit on the zero data points
    # zero_index = (labels != 0)
    # distribution = torch.distributions.normal.Normal(mu[zero_index], sigma[zero_index])
    # likelihood = distribution.log_prob(labels[zero_index])
    ###########################################################################################
    def nll_one_timestep(mu_one, sigma_one, labels_one):
        distribution = torch.distributions.normal.Normal(mu_one, sigma_one)
        likelihood = distribution.log_prob(labels_one)
        print(mu_one, labels_one)
        print(-likelihood)
        print("**************")
        return -torch.mean(likelihood)

    if len(mu.shape) == 1:
        # mu: (B,)
        return nll_one_timestep(mu, sigma, labels)
    elif len(mu.shape) == 2:
        # mu: (B, T)
        T = mu.shape[1]
        return sum(nll_one_timestep(mu[:, t], sigma[:, t], labels[:, t]) for t in range(T))


# def NLL_loss(mu: Variable, sigma: Variable, labels: Variable):
#     distribution = torch.distributions.normal.Normal(mu, sigma)
#     likelihood = distribution.log_prob(labels)
#     print(-likelihood)
#     print("**************")
#     return -torch.mean(likelihood)

In [14]:
mu = torch.tensor([
  [1, 1, 1],
  [1, 1, 1]
])

sigma = torch.tensor([
  [1,1,1],
  [1,1,1]
])

labels = torch.tensor([
  [1,3,4],
  [4,1,7]
])

NLL_loss(mu, sigma, labels)

tensor([1, 1]) tensor([1, 4])
tensor([0.9189, 5.4189])
**************
tensor([1, 1]) tensor([3, 1])
tensor([2.9189, 0.9189])
**************
tensor([1, 1]) tensor([4, 7])
tensor([ 5.4189, 18.9189])
**************


tensor(17.2568)